import { createElement } from '@lwc/engine-dom';
import Ex7MultipleInput from 'c/ex7MultipleInput';

describe('c-ex7-multiple-input', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-ex7-multiple-input', {
            is: Ex7MultipleInput
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});